on: [push]

jobs:
  test_local:
    runs-on: ubuntu-latest
    name: test-local
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: ./
        with:
          function_name: 'gh-action-test-lambda'
          number_to_keep: 100
  test-published:
    runs-on: ubuntu-latest
    name: test-published
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Test
        uses: kjs222/clean-old-lambda-versions-action@v0.2
        with:
          function_name: 'gh-action-test-lambda'
          number_to_keep: 2
